const colors = {
  primaryColor: '#ECEAE4',
  secondryColor: '#725054',
  tertiaryColor: '#e6e6e6',
};
const month = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];
const images = {
  femaleForDeathnews: require('../../assets/femaleDummy.webp'),
  noImage: require('../../assets/NoImage.jpeg'),
  mainPageBanner: require('../../assets/MainPageBanner.webp'),
  mainLogo: require('../../assets/logo.webp'),
  navBarLogo: require('../../assets/logo_navigator_icon.webp'),
};

const text = {
  mainFooterText:
    ' Khoja (Pirhai) Shia Isna Asheri Jamaat Karachi. All Rights Reserved.',
  deathNewsListTopText: `Innalillahi Wa Inna Ilayhi Raaji'oon \n"Surely we belong to God, and indeed to Him we shall return."(Al-Baqarah 2:156)`,
  appVersionErrorCaption:
    'An important update of this application is available on Play Store. Please update your application.',
  deathNewsShareHeaderText: `*ِإنَّا للهِ وَإِنَّا إِلَيْهِ رَاجِعُون*َ\nہم اللہ کے لئے ہیں اور اسی کی بارگاہ میں واپس جانے والے ہیں\nTo Allah do we belong, and to Him do we return\nWith heartfelt condolence we inform you that our following member has passed away:\n\n`,
  deathNewsShareFooterText: `\n\nIt is a recommended to give alms (sadqa) for the deceased and offer Fateha & Namaz-e-Wahshat-e-Qabr. May Allah (subhanu wata'ala) grant deceased maghfirat & vicinity of Ahlulbayt (alaihis salaam) in Jannah. Ameen`,
  deathNewsHeaderText:
    'إِنَّا للهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ \nہم اللہ کے لئے ہیں اور اسی کی بارگاہ میں واپس جانے والے ہیں \nTo Allah do we belong, and to Him do we return\nWith heartfelt condolence we inform you that our following member has passed away:',
  deathNewsFooterText: `It is a recommended to give alms (sadqa) for the deceased and offer Fateha & Namaz-e-Wahshat-e-Qabr.\nMay Allah (subhanu wata'ala) grant deceased maghfirat & vicinity of Ahlulbayt (alaihis salaam) in Jannah.\nAmeen`,
};

const appLink = {
  androidPlayStoreKpsiaj: 'market://details?id=com.kpsiaj',
};

let departmentsForFeedBack = [
  {label: 'Telethon', value: 'Telethon'},
  {label: 'About App', value: 'About App'},
  {label: 'Fatimiyah Education Network', value: 'Fatimiyah Education Network'},
  {label: 'Fatimiyah Hospital', value: 'Fatimiyah Hospital'},
  {label: 'Fatimiyah Sports Complex', value: 'Fatimiyah Sports Complex'},
  {label: 'Fatimiyah Community Center', value: 'Fatimiyah Community Center'},
  {
    label: 'Shaheed Hameed Ali Bhojani Hall',
    value: 'Shaheed Hameed Ali Bhojani Hall',
  },
  {label: 'Education Donation Box', value: 'Education Donation Box'},
  {label: 'Family Relations Committee', value: 'Family Relations Committee'},
  {label: 'Allama Haji Naji Library', value: 'Allama Haji Naji Library'},
  {label: 'Transport', value: 'Transport'},
  {label: 'KPSIAJ Front Desk', value: 'KPSIAJ Front Desk'},
  {label: 'Other', value: 'Other'},
];

let currencyValues = [
  {label: 'PKR', value: 'pkr'},
  {label: 'USD', value: 'usd'},
  {label: 'GBP', value: 'gbp'},
  {label: 'CAD', value: 'cad'},
  {label: 'AUD', value: 'aud'},
  {label: 'AED', value: 'aed'},
  {label: 'SAR', value: 'sar'},
  {label: 'IRR', value: 'irr'},
  {label: 'IQD', value: 'iqd'},
];
let donationTypeValues = [
  // {label: 'Donation', value: 'Donation'},
  {
    label: 'Khums full - Ayatullah Sistani',
    value: 'Khums full - Ayatullah Sistani',
  },
  {
    label: 'Khums Sehm e Imam (as) - Ayatullah Sistani',
    value: 'Khums Sehm e Imam (as) - Ayatullah Sistani',
  },
  {
    label: 'Khums Sehm e Sadaat - Ayatullah Sistani',
    value: 'Khums Sehm e Sadaat - Ayatullah Sistani',
  },
  {
    label: 'Khums full - Ayatullah Khamenai',
    value: 'Khums full - Ayatullah Khamenai',
  },
  {
    label: 'Khums Sehm e Imam (as) - Ayatullah Khamenai',
    value: 'Khums Sehm e Imam (as) - Ayatullah Khamenai',
  },
  {
    label: 'Khums Sehm e Sadaat - Ayatullah Khamenai',
    value: 'Khums Sehm e Sadaat - Ayatullah Khamenai',
  },
];
let dedicatedForValues = [
  // {label: 'General', value: 'General'},
  {label: 'Education', value: 'Education'},
  {label: 'Health', value: 'Health'},
  {label: 'Graveyard', value: 'Graveyard'},
  {label: 'Other', value: 'Other'},
];
const countryList = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas (the)',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory (the)',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands (the)',
  'Central African Republic (the)',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands (the)',
  'Colombia',
  'Comoros (the)',
  'Congo (the Democratic Republic of the)',
  'Congo (the)',
  'Cook Islands (the)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  "Côte d'Ivoire",
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic (the)',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands (the) [Malvinas]',
  'Faroe Islands (the)',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories (the)',
  'Gabon',
  'Gambia (the)',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See (the)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea (the Democratic People's Republic of)",
  'Korea (the Republic of)',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic (the)",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands (the)',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Moldova (the Republic of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands (the)',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger (the)',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands (the)',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines (the)',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of North Macedonia',
  'Romania',
  'Russian Federation (the)',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan (the)',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan (Province of China)',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands (the)',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates (the)',
  'United Kingdom of Great Britain and Northern Ireland (the)',
  'United States Minor Outlying Islands (the)',
  'United States of America (the)',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands',
];

let countryObjInArray = [];
for (var key in countryList) {
  countryObjInArray.push({label: countryList[key], value: countryList[key]});
}

export {
  countryObjInArray,
  dedicatedForValues,
  donationTypeValues,
  currencyValues,
  departmentsForFeedBack,
  colors,
  images,
  text,
  appLink,
  month,
};
